### ISSUE TITLE
Unable to find MQ C library - dockerfile and npm install

### ISSUE THREAD

**Issue by rk-servian** [ibm-messaging/mq-mqi-nodejs#119]
Unable to find MQ C library despite doing npm install through docker file. Getting the following error:

Version: ^0.9.17

Node image used: 14.15.4-alpine3.12 in docker

```
Cannot find MQ C library.
  Has the C client been installed?
  Have you run setmqenv?

/opt/node_modules/ffi-napi/lib/dynamic_library.js:75
    throw new Error('Dynamic Linking Error: ' + err);
          ^
Error: Dynamic Linking Error: Error loading shared library /opt/mqm/lib/libmqm_r.so: No such file or directory
    at new DynamicLibrary (/opt/node_modules/ffi-napi/lib/dynamic_library.js:75:11)
    at Object.Library (/opt/node_modules/ffi-napi/lib/library.js:47:10)
    at loadLib (/opt/node_modules/ibmmq/lib/mqi.js:288:18)
    at loadLibMulti (/opt/node_modules/ibmmq/lib/mqi.js:403:13)
    at Object.<anonymous> (/opt/node_modules/ibmmq/lib/mqi.js:421:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.require.extensions.<computed> [as .js] (/opt/node_modules/ts-node/src/index.ts:1045:43)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at Module.patchedRequire [as require] (/opt/node_modules/diagnostic-channel/dist/src/patchRequire.js:14:46)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/opt/src/modules/client/Client.ts:28:15)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Module.m._compile (/opt/node_modules/ts-node/src/index.ts:1056:23)
```

**Comment by ibmmqmet** [comment]
Alpine linux has its own libc implementation. The MQ client code has not been compiled against that libc and will not load. That's why the Dockerfile sample in this repo uses a base image with the standard glibc.

**Comment by rk-servian** [comment]
@ibmmqmet As suggested, I went ahead with a debian-stretch-slim node 14 distribution. And I can see the redist packages along inside node_modules/ibmmq. But when attempting to make a connection, I'm getting the following error:
```
AMQ6300E: Directory '/home/es/IBM' could not be created: 'EROFS - Read-only file system'.
ERROR:  MQError: CONNX: MQCC = MQCC_FAILED [2] MQRC = MQRC_CONNECTION_BROKEN [2009]
    at /opt/app/node_modules/ibmmq/lib/mqi.js:776:17
    at Object.<anonymous> (/opt/app/node_modules/ffi-napi/lib/_foreign_function.js:115:9)
    at Object.callbackTrampoline (internal/async_hooks.js:134:14) {
  mqcc: 2,
  mqccstr: 'MQCC_FAILED',
  mqrc: 2009,
  mqrcstr: 'MQRC_CONNECTION_BROKEN',
  version: '0.9.17',
  verb: 'CONNX'
}
```

**Comment by ibmmqmet** [comment]
See #49 - either use the referenced environment variable or make that directory writable.
See also https://github.com/ibm-messaging/mq-metric-samples/pull/59 which added something similar for Go packages.

**Comment by rk-servian** [comment]
@ibmmqmet Thanks a lot for your help! The Go package reference worked like a charm! :) 
Closing the issue
