### ISSUE TITLE
Buffer instance must be at least 364 bytes

### ISSUE THREAD

**Issue by mortenLom** [ibm-messaging/mq-mqi-nodejs#12]
Hi
amqsput.js works, but amqsgeta.js gives me this error:

/home/morten/workspace/ibmmq-test/node_modules/ffi/lib/callback.js:20
        throw err
        ^
AssertionError [ERR_ASSERTION]: Buffer instance must be at least 364 bytes to back this struct type
    at new StructType (/home/morten/workspace/ibmmq-test/node_modules/ref-struct/lib/struct.js:84:7)
    at Function.get (/home/morten/workspace/ibmmq-test/node_modules/ref-struct/lib/struct.js:158:10)
    at Object.get (/home/morten/workspace/ibmmq-test/node_modules/ref/lib/ref.js:452:17)
    at Object.deref (/home/morten/workspace/ibmmq-test/node_modules/ref/lib/ref.js:660:18)
    at mqiCB (/home/morten/workspace/ibmmq-test/node_modules/ibmmq/lib/mqi.js:1101:18)
    at /home/morten/workspace/ibmmq-test/node_modules/ffi/lib/callback.js:66:25

Do you know why I get this error? Thanks for any help.
Morten

**Comment by mortenLom** [comment]
I don't get this error when I use synchronous get: amqsget.js. Could it be because amqsgeta.js is missing:
  var buf = Buffer.alloc(1024) ?:
Morten

**Comment by ibmmqmet** [comment]
This looks to be because on an MQ client (instead of local qmgr), the code is apparently not correctly handling some additional flows that come into the callback function. I'll need to see how to fix it.

**Comment by ibmmqmet** [comment]
I've pushed a change out that ought to fix this.

**Comment by mortenLom** [comment]
Great. Thanks :-)
