### ISSUE TITLE
Cannot find MQ C library : Error loading shared library /opt/mqm/lib/libmqm_r.so 

### ISSUE THREAD

**Issue by nidhiag** [ibm-messaging/mq-mqi-nodejs#159]
i am trying to run ibmmq with alpine@node18 

Base Image : node:18.14.2-alpine
Setting the LD_LIBRARY_PATH 
Getting the below logs : 
```
{"message":"Dynamic Linking Error: Error loading shared library /opt/mqm/lib/libmqm_r.so: No such file or directory","name":"Error","stack":"Error: Dynamic Linking Error: Error loading shared library /opt/mqm/lib/libmqm_r.so: No such file or directory\n    at new DynamicLibrary (/opt/ibm/app/node_modules/ffi-napi/lib/dynamic_library.js:75:11)\n    at Object.Library (/opt/ibm/app/node_modules/ffi-napi/lib/library.js:47:10)\n    at loadLib (/opt/ibm/app/node_modules/ibmmq/lib/mqi.js:290:18)\n    at loadLibMulti (/opt/ibm/app/node_modules/ibmmq/lib/mqi.js:417:13)\n    at Object.<anonymous> (/opt/ibm/app/node_modules/ibmmq/lib/mqi.js:436:1)\n    at Module._compile (node:internal/modules/cjs/loader:1254:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)\n    at Module.load (node:internal/modules/cjs/loader:1117:32)\n    at Module._load (node:internal/modules/cjs/loader:958:12)\n    at Module.require (node:internal/modules/cjs/loader:1141:19)\n    at require (node:internal/modules/cjs/helpers:110:18)\n    at Object.<anonymous> (/opt/ibm/app/node_modules/@ibm-app-connect/loopback-connector-ibmmq/lib/resourceClasses/hObj.js:9:12)\n    at Module._compile (node:internal/modules/cjs/loader:1254:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)\n    at Module.load (node:internal/modules/cjs/loader:1117:32)\n    at Module._load (node:internal/modules/cjs/loader:958:12)"}
```
Please let me know if any more changes needs to be done.

**Comment by ibmmqmet** [comment]
Don't use an alpine base image. See #119.

**Comment by nidibm** [comment]
@ibmmqmet So compilation on alpine base images are not supported .

**Comment by ibmmqmet** [comment]
As the referenced issue states, the MQ client cannot run on alpine/musl systems. Nothing to do with this package; it's the underlying C code that requires glibc.

**Comment by nidibm** [comment]
Please close this issue.
