### ISSUE TITLE
Can't get to work

### ISSUE THREAD

**Issue by kdunetz** [ibm-messaging/mq-mqi-nodejs#30]
Getting this error when running.  Also, can't find this program: setmqenv

/Users/kevindunetz/Documents/kubernetes/apps/mq-mqi-nodejs/samples/node_modules/ffi/lib/dynamic_library.js:74
    throw new Error('Dynamic Linking Error: ' + err)
    ^

Error: Dynamic Linking Error: dlopen(libmqm_r.dylib, 2): image not found
    at new DynamicLibrary (/Users/kevindunetz/Documents/kubernetes/apps/mq-mqi-nodejs/samples/node_modules/ffi/lib/dynamic_library.js:74:11)
    at Object.Library (/Users/kevindunetz/Documents/kubernetes/apps/mq-mqi-nodejs/samples/node_modules/ffi/lib/library.js:45:12)
    at Object.<anonymous> (/Users/kevindunetz/Documents/kubernetes/apps/mq-mqi-nodejs/samples/node_modules/ibmmq/lib/mqi.js:157:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)

**Comment by fjbsaper** [comment]
Did you install the MQ Client on your image? If not that would explain your errors.

**Comment by ibmmqmet** [comment]
You need to install the MQ C client package for the underlying libraries and the setmqenv command. I've updated the README to give links on how you can get that.
