### ISSUE TITLE
Unable to integrate with AWS nodejs lambda

### ISSUE THREAD

**Issue by anilbhaskaran** [ibm-messaging/mq-mqi-nodejs#37]
Hi,

I am trying to use the module with AWS lambda. I am getting the below run time error.
module initialization error: Error
at Error (native)
at Object.Module._extensions..node (module.js:597:18)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:438:3)
at Module.require (module.js:497:17)
at require (internal/module.js:20:19)
at bindings (/var/task/node_modules/bindings/bindings.js:81:44)
at Object.<anonymous> (/var/task/node_modules/ref/lib/ref.js:5:47)
at Module._compile (module.js:570:32)

It is working fine with a standalone nodejs program and windows build tools installed. Please let me know what are dependencies required to make it work with AWS lambda.

**Comment by akash-sethi** [comment]
Any update on this?

**Comment by ibmmqmet** [comment]
Closing for inactivity - noone seems to have any advice.
