### ISSUE TITLE
Incompatible with node 10

### ISSUE THREAD

**Issue by simonihmig** [ibm-messaging/mq-mqi-nodejs#44]
I am able to successfully `yarn add ibmmq` (latest 0.7.1) with node 6 and 8, with the latest node 10.5 I get a compilation error however:

<details>
  <summary><code>> yarn add ibmmq</code> (Click to expand)</summary>

```
yarn add v1.5.1
(node:6968) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
[4/5] 🔗  Linking dependencies...
[5/5] 📃  Building fresh packages...
[2/3] ⢀ ffi:                                        ^
[-/3] ⢀ waiting...
[-/3] ⢀ waiting...
[-/3] ⢀ waiting...
error An unexpected error occurred: "/Users/simonihmig/Projects/sit-app/core-api/node_modules/ffi: Command failed.
Exit code: 1
Command: sh
Arguments: -c node-gyp rebuild
Directory: /Users/simonihmig/Projects/sit-app/core-api/node_modules/ffi
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@10.5.0 | darwin | x64
gyp info spawn /usr/bin/python
gyp info spawn args [ '/Users/simonihmig/.nvm/versions/node/v10.5.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/simonihmig/Projects/sit-app/core-api/node_modules/ffi/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/simonihmig/.nvm/versions/node/v10.5.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/simonihmig/.node-gyp/10.5.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/simonihmig/.node-gyp/10.5.0',
gyp info spawn args   '-Dnode_gyp_dir=/Users/simonihmig/.nvm/versions/node/v10.5.0/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/simonihmig/.node-gyp/10.5.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/simonihmig/Projects/sit-app/core-api/node_modules/ffi',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CC(target) Release/obj.target/ffi/deps/libffi/src/prep_cif.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/types.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/raw_api.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/java_raw_api.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/closures.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/ffi.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/ffi64.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/darwin.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/darwin64.o
  LIBTOOL-STATIC Release/libffi.a
  CXX(target) Release/obj.target/ffi_bindings/src/ffi.o
../src/ffi.cc:58:3: warning: 'ForceSet' is deprecated [-Wdeprecated-declarations]
  SET_ENUM_VALUE(FFI_OK);
  ^
../src/ffi.cc:38:8: note: expanded from macro 'SET_ENUM_VALUE'
  Nan::ForceSet(target, Nan::New<String>(#_value).ToLocalChecked(), \\
       ^
../../nan/nan_maybe_43_inl.h:130:1: note: 'ForceSet' has been explicitly marked deprecated here
NAN_DEPRECATED inline Maybe<bool> ForceSet(
^
../../nan/nan.h:98:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/ffi.cc:59:3: warning: 'ForceSet' is deprecated [-Wdeprecated-declarations]
  SET_ENUM_VALUE(FFI_BAD_TYPEDEF);
  ^
../src/ffi.cc:38:8: note: expanded from macro 'SET_ENUM_VALUE'
  Nan::ForceSet(target, Nan::New<String>(#_value).ToLocalChecked(), \\
       ^
../../nan/nan_maybe_43_inl.h:130:1: note: 'ForceSet' has been explicitly marked deprecated here
NAN_DEPRECATED inline Maybe<bool> ForceSet(
^
../../nan/nan.h:98:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/ffi.cc:60:3: warning: 'ForceSet' is deprecated [-Wdeprecated-declarations]
  SET_ENUM_VALUE(FFI_BAD_ABI);
  ^
../src/ffi.cc:38:8: note: expanded from macro 'SET_ENUM_VALUE'
  Nan::ForceSet(target, Nan::New<String>(#_value).ToLocalChecked(), \\
       ^
../../nan/nan_maybe_43_inl.h:130:1: note: 'ForceSet' has been explicitly marked deprecated here
NAN_DEPRECATED inline Maybe<bool> ForceSet(
^
../../nan/nan.h:98:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/ffi.cc:63:3: warning: 'ForceSet' is deprecated [-Wdeprecated-declarations]
  SET_ENUM_VALUE(FFI_DEFAULT_ABI);
  ^
../src/ffi.cc:38:8: note: expanded from macro 'SET_ENUM_VALUE'
  Nan::ForceSet(target, Nan::New<String>(#_value).ToLocalChecked(), \\
       ^
../../nan/nan_maybe_43_inl.h:130:1: note: 'ForceSet' has been explicitly marked deprecated here
NAN_DEPRECATED inline Maybe<bool> ForceSet(
^
../../nan/nan.h:98:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/ffi.cc:64:3: warning: 'ForceSet' is deprecated [-Wdeprecated-declarations]
  SET_ENUM_VALUE(FFI_FIRST_ABI);
  ^
../src/ffi.cc:38:8: note: expanded from macro 'SET_ENUM_VALUE'
  Nan::ForceSet(target, Nan::New<String>(#_value).ToLocalChecked(), \\
       ^
../../nan/nan_maybe_43_inl.h:130:1: note: 'ForceSet' has been explicitly marked deprecated here
NAN_DEPRECATED inline Maybe<bool> ForceSet(
^
../../nan/nan.h:98:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/ffi.cc:65:3: warning: 'ForceSet' is deprecated [-Wdeprecated-declarations]
  SET_ENUM_VALUE(FFI_LAST_ABI);
  ^
../src/ffi.cc:38:8: note: expanded from macro 'SET_ENUM_VALUE'
  Nan::ForceSet(target, Nan::New<String>(#_value).ToLocalChecked(), \\
       ^
../../nan/nan_maybe_43_inl.h:130:1: note: 'ForceSet' has been explicitly marked deprecated here
NAN_DEPRECATED inline Maybe<bool> ForceSet(
^
../../nan/nan.h:98:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/ffi.cc:81:3: warning: 'ForceSet' is deprecated [-Wdeprecated-declarations]
  SET_ENUM_VALUE(FFI_SYSV);
  ^
../src/ffi.cc:38:8: note: expanded from macro 'SET_ENUM_VALUE'
  Nan::ForceSet(target, Nan::New<String>(#_value).ToLocalChecked(), \\
       ^
../../nan/nan_maybe_43_inl.h:130:1: note: 'ForceSet' has been explicitly marked deprecated here
NAN_DEPRECATED inline Maybe<bool> ForceSet(
^
../../nan/nan.h:98:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/ffi.cc:83:3: warning: 'ForceSet' is deprecated [-Wdeprecated-declarations]
  SET_ENUM_VALUE(FFI_UNIX64);
  ^
../src/ffi.cc:38:8: note: expanded from macro 'SET_ENUM_VALUE'
  Nan::ForceSet(target, Nan::New<String>(#_value).ToLocalChecked(), \\
       ^
../../nan/nan_maybe_43_inl.h:130:1: note: 'ForceSet' has been explicitly marked deprecated here
NAN_DEPRECATED inline Maybe<bool> ForceSet(
^
../../nan/nan.h:98:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/ffi.cc:88:3: warning: 'ForceSet' is deprecated [-Wdeprecated-declarations]
  SET_ENUM_VALUE(RTLD_LAZY);
  ^
../src/ffi.cc:38:8: note: expanded from macro 'SET_ENUM_VALUE'
  Nan::ForceSet(target, Nan::New<String>(#_value).ToLocalChecked(), \\
       ^
../../nan/nan_maybe_43_inl.h:130:1: note: 'ForceSet' has been explicitly marked deprecated here
NAN_DEPRECATED inline Maybe<bool> ForceSet(
^
../../nan/nan.h:98:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/ffi.cc:91:3: warning: 'ForceSet' is deprecated [-Wdeprecated-declarations]
  SET_ENUM_VALUE(RTLD_NOW);
  ^
../src/ffi.cc:38:8: note: expanded from macro 'SET_ENUM_VALUE'
  Nan::ForceSet(target, Nan::New<String>(#_value).ToLocalChecked(), \\
       ^
../../nan/nan_maybe_43_inl.h:130:1: note: 'ForceSet' has been explicitly marked deprecated here
NAN_DEPRECATED inline Maybe<bool> ForceSet(
^
../../nan/nan.h:98:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/ffi.cc:94:3: warning: 'ForceSet' is deprecated [-Wdeprecated-declarations]
  SET_ENUM_VALUE(RTLD_LOCAL);
  ^
../src/ffi.cc:38:8: note: expanded from macro 'SET_ENUM_VALUE'
  Nan::ForceSet(target, Nan::New<String>(#_value).ToLocalChecked(), \\
       ^
../../nan/nan_maybe_43_inl.h:130:1: note: 'ForceSet' has been explicitly marked deprecated here
NAN_DEPRECATED inline Maybe<bool> ForceSet(
^
../../nan/nan.h:98:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/ffi.cc:97:3: warning: 'ForceSet' is deprecated [-Wdeprecated-declarations]
  SET_ENUM_VALUE(RTLD_GLOBAL);
  ^
../src/ffi.cc:38:8: note: expanded from macro 'SET_ENUM_VALUE'
  Nan::ForceSet(target, Nan::New<String>(#_value).ToLocalChecked(), \\
       ^
../../nan/nan_maybe_43_inl.h:130:1: note: 'ForceSet' has been explicitly marked deprecated here
NAN_DEPRECATED inline Maybe<bool> ForceSet(
^
../../nan/nan.h:98:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/ffi.cc:100:3: warning: 'ForceSet' is deprecated [-Wdeprecated-declarations]
  SET_ENUM_VALUE(RTLD_NOLOAD);
  ^
../src/ffi.cc:38:8: note: expanded from macro 'SET_ENUM_VALUE'
  Nan::ForceSet(target, Nan::New<String>(#_value).ToLocalChecked(), \\
       ^
../../nan/nan_maybe_43_inl.h:130:1: note: 'ForceSet' has been explicitly marked deprecated here
NAN_DEPRECATED inline Maybe<bool> ForceSet(
^
../../nan/nan.h:98:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/ffi.cc:103:3: warning: 'ForceSet' is deprecated [-Wdeprecated-declarations]
  SET_ENUM_VALUE(RTLD_NODELETE);
  ^
../src/ffi.cc:38:8: note: expanded from macro 'SET_ENUM_VALUE'
  Nan::ForceSet(target, Nan::New<String>(#_value).ToLocalChecked(), \\
       ^
../../nan/nan_maybe_43_inl.h:130:1: note: 'ForceSet' has been explicitly marked deprecated here
NAN_DEPRECATED inline Maybe<bool> ForceSet(
^
../../nan/nan.h:98:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/ffi.cc:106:3: warning: 'ForceSet' is deprecated [-Wdeprecated-declarations]
  SET_ENUM_VALUE(RTLD_FIRST);
  ^
../src/ffi.cc:38:8: note: expanded from macro 'SET_ENUM_VALUE'
  Nan::ForceSet(target, Nan::New<String>(#_value).ToLocalChecked(), \\
       ^
../../nan/nan_maybe_43_inl.h:130:1: note: 'ForceSet' has been explicitly marked deprecated here
NAN_DEPRECATED inline Maybe<bool> ForceSet(
^
../../nan/nan.h:98:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/ffi.cc:111:11: error: no member named 'ForceSet' in 'v8::Object'
  target->ForceSet(Nan::New<String>(\"RTLD_NEXT\").ToLocalChecked(), WrapPointer((char *)RTLD_NEXT), static_cast<PropertyAttribute>(ReadOnly | DontDelete));
  ~~~~~~  ^
../src/ffi.cc:114:11: error: no member named 'ForceSet' in 'v8::Object'
  target->ForceSet(Nan::New<String>(\"RTLD_DEFAULT\").ToLocalChecked(), WrapPointer((char *)RTLD_DEFAULT), static_cast<PropertyAttribute>(ReadOnly | DontDelete));
  ~~~~~~  ^
../src/ffi.cc:117:11: error: no member named 'ForceSet' in 'v8::Object'
  target->ForceSet(Nan::New<String>(\"RTLD_SELF\").ToLocalChecked(), WrapPointer((char *)RTLD_SELF), static_cast<PropertyAttribute>(ReadOnly|DontDelete));
  ~~~~~~  ^
../src/ffi.cc:120:11: error: no member named 'ForceSet' in 'v8::Object'
  target->ForceSet(Nan::New<String>(\"RTLD_MAIN_ONLY\").ToLocalChecked(), WrapPointer((char *)RTLD_MAIN_ONLY), static_cast<PropertyAttribute>(ReadOnly|DontDelete));
  ~~~~~~  ^
../src/ffi.cc:123:11: error: no member named 'ForceSet' in 'v8::Object'
  target->ForceSet(Nan::New<String>(\"FFI_ARG_SIZE\").ToLocalChecked(), Nan::New<Uint32>((uint32_t)sizeof(ffi_arg)), static_cast<PropertyAttribute>(ReadOnly|DontDelete));
  ~~~~~~  ^
../src/ffi.cc:124:11: error: no member named 'ForceSet' in 'v8::Object'
  target->ForceSet(Nan::New<String>(\"FFI_SARG_SIZE\").ToLocalChecked(), Nan::New<Uint32>((uint32_t)sizeof(ffi_sarg)), static_cast<PropertyAttribute>(ReadOnly | DontDelete));
  ~~~~~~  ^
../src/ffi.cc:125:11: error: no member named 'ForceSet' in 'v8::Object'
  target->ForceSet(Nan::New<String>(\"FFI_TYPE_SIZE\").ToLocalChecked(), Nan::New<Uint32>((uint32_t)sizeof(ffi_type)), static_cast<PropertyAttribute>(ReadOnly | DontDelete));
  ~~~~~~  ^
../src/ffi.cc:126:11: error: no member named 'ForceSet' in 'v8::Object'
  target->ForceSet(Nan::New<String>(\"FFI_CIF_SIZE\").ToLocalChecked(), Nan::New<Uint32>((uint32_t)sizeof(ffi_cif)), static_cast<PropertyAttribute>(ReadOnly | DontDelete));
  ~~~~~~  ^
../src/ffi.cc:132:11: error: no member named 'ForceSet' in 'v8::Object'
  target->ForceSet(Nan::New<String>(\"HAS_OBJC\").ToLocalChecked(), Nan::New<Boolean>(hasObjc), static_cast<PropertyAttribute>(ReadOnly | DontDelete));
  ~~~~~~  ^
../src/ffi.cc:367:16: warning: 'Call' is deprecated [-Wdeprecated-declarations]
  p->callback->Call(1, argv);
               ^
../../nan/nan.h:1617:3: note: 'Call' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value>
  ^
../../nan/nan.h:98:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
16 warnings and 9 errors generated.
make: *** [Release/obj.target/ffi_bindings/src/ffi.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/simonihmig/.nvm/versions/node/v10.5.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Darwin 17.3.0
gyp ERR! command \"/Users/simonihmig/.nvm/versions/node/v10.5.0/bin/node\" \"/Users/simonihmig/.nvm/versions/node/v10.5.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js\" \"rebuild\"
gyp ERR! cwd /Users/simonihmig/Projects/sit-app/core-api/node_modules/ffi
gyp ERR! node -v v10.5.0
```
</details>

**Comment by ibmmqmet** [comment]
This is because of a [known problem](https://github.com/node-ffi/node-ffi/issues/468) in the ffi package. Fixes to that problem have not been pushed out.

There is also a [separate PR](https://github.com/ibm-messaging/mq-mqi-nodejs/pull/42) submitted to this repo to deal with it in a different way that I am currently testing out but have not yet approved.

**Comment by simonihmig** [comment]
Confirmed, this indeed fixes the problem. Thanks @ibmmqmet!
