### ISSUE TITLE
Need some help on the sample

### ISSUE THREAD

**Issue by mortenLom** [ibm-messaging/mq-mqi-nodejs#5]
Hi
I have installed:
rpm -ivh MQSeriesRuntime-9.0.0-2.x86_64.rpm
rpm -ivh MQSeriesClient-9.0.0-2.x86_64.rpm
and 
ibmmq on CentOS.
Now I am trying the sample towards an MQ server running on a different machine.
I have set:
MQSERVER=NITRA.CLCH/TCP/’134.47.105.10’
Then I run the command: node amqsget.js QA.TEST07.FHS_NITRA_RESOURCE_REP M06T
I get the following error:

[morten@localhost samples]$ node amqsget.js QA.TEST07.FHS_NITRA_RESOURCE_REP M06T
/home/morten/Downloads/mq-mqi-nodejs-master/node_modules/bindings/bindings.js:91
  throw err
  ^

Error: Could not locate the bindings file. Tried:
 → /home/morten/Downloads/mq-mqi-nodejs-master/node_modules/ref/build/binding.node
 → /home/morten/Downloads/mq-mqi-nodejs-master/node_modules/ref/build/Debug/binding.node
 → /home/morten/Downloads/mq-mqi-nodejs-master/node_modules/ref/build/Release/binding.node
 → /home/morten/Downloads/mq-mqi-nodejs-master/node_modules/ref/out/Debug/binding.node
 → /home/morten/Downloads/mq-mqi-nodejs-master/node_modules/ref/Debug/binding.node
 → /home/morten/Downloads/mq-mqi-nodejs-master/node_modules/ref/out/Release/binding.node
 → /home/morten/Downloads/mq-mqi-nodejs-master/node_modules/ref/Release/binding.node
 → /home/morten/Downloads/mq-mqi-nodejs-master/node_modules/ref/build/default/binding.node
 → /home/morten/Downloads/mq-mqi-nodejs-master/node_modules/ref/compiled/8.9.1/linux/x64/binding.node
    at bindings (/home/morten/Downloads/mq-mqi-nodejs-master/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/home/morten/Downloads/mq-mqi-nodejs-master/node_modules/ref/lib/ref.js:5:47)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/morten/Downloads/mq-mqi-nodejs-master/lib/mqi.js:57:11)

Do you know what my problem is?

Morten

**Comment by ibmmqmet** [comment]
I don't know what the problem is, but google suggests that
```
  sudo npm install -g node-gyp
  sudo node-gyp rebuild
```
may help.
