### ISSUE TITLE
Different behavior on different OS

### ISSUE THREAD

**Issue by alexdeia** [ibm-messaging/mq-mqi-nodejs#83]
Hi!

I see different behavior on MacOS and Debian (node:12-slim).
Node version the same. (by the way, on v13.10.1 doesn't work at all).
```bash
node -v
v12.16.2
```
IBM Toolkits:
On Mac - 9.1.5.0-IBM-MQ-Toolkit-MacX64.tar.gz
On Debian - 9.1.5.0-IBM-MQC-Redist-LinuxX64.tar.gz

Lib:
ibmmq@0.9.13

On MacOS everything is ok:
```bash
node getMessage.js
Sample AMQSGETA.JS start
MQCONN to <CONN Name> successful 
MQOPEN of <Queue Name> successful
MQSTR was NOT detected!
test sync
^CCaught interrupt signal
MQCLOSE successful
MQDISC successful
```

On Debian (docker container) I see the following error:
```bash
node getMessage.js
Sample AMQSGETA.JS start
MQCONN to <CONN Name> successful 
MQOPEN of <Queue Name> successful
MQError: GET: MQCC = MQCC_WARNING [1] MQRC = MQRC_FORMAT_ERROR [2110]
    at /usr/src/app/node_modules/ibmmq/lib/mqi.js:2187:18
    at Object.<anonymous> (/usr/src/app/node_modules/ffi-napi/lib/_foreign_function.js:115:9) {
  name: 'MQError',
  message: 'GET: MQCC = MQCC_WARNING [1] MQRC = MQRC_FORMAT_ERROR [2110]',
  mqcc: 1,
  mqccstr: 'MQCC_WARNING',
  mqrc: 2110,
  mqrcstr: 'MQRC_FORMAT_ERROR',
  version: '0.9.13',
  verb: 'GET'
}
MQ call failed at GET: MQCC = MQCC_WARNING [1] MQRC = MQRC_FORMAT_ERROR [2110]
Exiting ...
MQCLOSE successful
```
I have a question: why I get an error, if everything is the same except OS and MQ toolkit (maybe it is the main reason) ?

You can see the code below.
I took an example from the samples and made a few changes:
```javascript
'use strict';

const zlib = require('zlib');
const util = require('util');

const unzipAsync = util.promisify(zlib.unzip);

// Import the MQ package
var mq = require('ibmmq');
var MQC = mq.MQC; // Want to refer to this export directly for simplicity

// The default queue manager and queue to be used
var qMgr = "...";
var qName = "..."
var msgId = null;

// remote queue
var cno = new mq.MQCNO();
var cd = new mq.MQCD();
cd.ConnectionName = '...';
cd.ChannelName = '...';
cno.ClientConn = cd;

// Some global variables
var connectionHandle;
var queueHandle;

var ok = true;
var exitCode = 0;

/*
 * Format any error messages
 */
function formatErr(err) {
  if (err) {
    ok = false;
    return "MQ call failed at " + err.message;
  } else {
    return "MQ call successful";
  }
}

function hexToBytes(hex) {
    for (var bytes = [], c = 0; c < hex.length; c += 2)
    bytes.push(parseInt(hex.substr(c, 2), 16));
    return bytes;
}


/*
 * Define which messages we want to get, and how.
 */
function getMessages() {
  var md = new mq.MQMD();
  var gmo = new mq.MQGMO();

  gmo.Options = MQC.MQGMO_NO_SYNCPOINT |
                MQC.MQGMO_WAIT |
                MQC.MQGMO_CONVERT |
                MQC.MQGMO_FAIL_IF_QUIESCING;
  gmo.MatchOptions = MQC.MQMO_NONE;
  gmo.WaitInterval = MQC.MQWI_UNLIMITED;
console.log(gmo);
  if (msgId != null) {
     console.log("Setting Match Option for MsgId");
     gmo.MatchOptions = MQC.MQMO_MATCH_MSG_ID;
     md.MsgId = hexToBytes(msgId);
  }

  // Set up the callback handler to be invoked when there
  // are any incoming messages. As this is a sample, I'm going
  // to tune down the poll interval from default 10 seconds to 0.5s.
  mq.setTuningParameters({getLoopPollTimeMs: 5000});
  mq.Get(queueHandle,md,gmo,getCB);

}

/*
 * This function is the async callback. Parameters
 * include the message descriptor and the buffer containing
 * the message data.
 */

async function getCB(err, hObj, gmo,md,buf, hConn) {
   // If there is an error, prepare to exit by setting the ok flag to false.
   if (err) {
     if (err.mqrc == MQC.MQRC_NO_MSG_AVAILABLE) {
       console.log("No more messages available.");
     } else {
       console.log(formatErr(err));
       exitCode = 1;
     }
     ok = false;
     // We don't need any more messages delivered, so cause the
     // callback to be deleted after this one has completed.
     mq.GetDone(hObj);
   } else {
      if (md.Format === 'MQSTR') {
        // console.log("message <%s>", decoder.write(buf));
        console.log('MQSTR was detected.');
        const dataBuffer = await unzipAsync(buf)
        const data = dataBuffer.toString('utf8');
        console.log(data);
     } else {
        // console.log("binary message: " + buf);
        console.log('MQSTR was NOT detected!');
        const dataBuffer = await unzipAsync(buf)
        const data = dataBuffer.toString('utf8');
        console.log(data);
     }
  }
}

/*
 * When we're done, close any queues and connections.
 */
function cleanup(hConn,hObj) {
  mq.Close(hObj, 0, function(err) {
    if (err) {
      console.log(formatErr(err));
    } else {
      console.log("MQCLOSE successful");
    }
    mq.Disc(hConn, function(err) {
      if (err) {
        console.log(formatErr(err));
      } else {
        console.log("MQDISC successful");
      }
    });
  });
}

/**************************************************************
 * The program really starts here.
 * Connect to the queue manager. If that works, the callback function
 * opens the queue, and then we can start to retrieve messages.
 */
console.log("Sample AMQSGETA.JS start");

mq.setTuningParameters({syncMQICompat:true});


// Connect to the queue manager, including a callback function for
// when it completes.
mq.Connx(qMgr, cno, function(err,hConn) {
   if (err) {
     console.log(formatErr(err));
     ok = false;
   } else {
     console.log("MQCONN to %s successful ", qMgr);
     connectionHandle = hConn;

     // Define what we want to open, and how we want to open it.
     var od = new mq.MQOD();
     od.ObjectName = qName;
     od.ObjectType = MQC.MQOT_Q;
     var openOptions = MQC.MQOO_INPUT_AS_Q_DEF;
     mq.Open(hConn,od,openOptions,function(err,hObj) {
       queueHandle = hObj;
       if (err) {
         console.log(formatErr(err));
       } else {
         console.log("MQOPEN of %s successful",qName);
         // And now we can ask for the messages to be delivered.
         getMessages();
       }
     });
   }
});

process.on('SIGINT', function() {
  console.log("Caught interrupt signal");

  cleanup(connectionHandle,queueHandle);
  process.exit(exitCode);
});
```

**Comment by ibmmqmet** [comment]
MQRC_FORMAT_ERROR is described in the [KnowledgeCentre](https://www.ibm.com/support/knowledgecenter/SSFKSJ_9.1.0/com.ibm.mq.tro.doc/q041710_.htm) alaong with its reasons.

You don't say how the messages are being put, but since you seem to be sending zipped data, then I assume the messages have got MQFMT_NONE set. And so trying to use MQGMO_CONVERT is not appropriate. You should never set that option when you are expecting to process MQFMT_NONE messages.

The reason for the different responses is likely that on MacOS, the client program is running with the same codepage (ccsid) as the original message was labelled with when it was put. So the GMO option is essentially ignored. On Linux, however, a different codepage is in effect and hence the qmgr tries to convert it and gives up with a warning.

**Comment by alexdeia** [comment]
At first glance, without MQC.MQGMO_CONVERT it worked (on Mac and on Debian) !  Mark, thank you so much!

About put the message. I use the sample amqsputp.js plus compress:

```javascript
...

mq.ConnxPromise(qMgr, cno)
  .then(hConn=>{
        console.log("MQCONN to %s successful ", qMgr);
        ghConn = hConn;
        var od = new mq.MQOD();
        od.ObjectName = qName;
        od.ObjectType = MQC.MQOT_Q;
        var openOptions = MQC.MQOO_OUTPUT;
        return mq.OpenPromise(hConn,od,openOptions);
        })
  .then(async hObj=> {
        console.log("MQOPEN of %s successful",qName);
        const compressed = zlib.gzipSync('test sync');
        var mqmd = new mq.MQMD(); // Defaults are fine.
        var pmo = new mq.MQPMO();
        // Describe how the Put should behave
        pmo.Options = MQC.MQPMO_NO_SYNCPOINT |
                      MQC.MQPMO_NEW_MSG_ID |
                      MQC.MQPMO_NEW_CORREL_ID;

        ghObj = hObj;
        
        return mq.PutPromise(hObj,mqmd,pmo,compressed);
...
```
