### ISSUE TITLE
Failed to build ibmmq module (ffi-napi dependency error)

### ISSUE THREAD

**Issue by miguelmartinezinf** [ibm-messaging/mq-mqi-nodejs#96]
I am having the following error when trying to install my project dependencies (`npm i`) (where "`ibmmq": "0.9.14",` is included). It seems to be related to the version of `ffi-napi`, since this module is not compatible with <10.22 version of node.

### Versions 
* mq-mqi-nodejs : 0.9.14
* nodejs: 10.18.11

```
Step 9/9 : RUN npm install
 ---> Running in 53b34e28bea5
npm WARN deprecated mkdirp@0.5.4: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated request-promise-native@1.0.7: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated request@2.88.0: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated @opentelemetry/types@0.2.0: Package renamed to @opentelemetry/api, see https://github.com/open-telemetry/opentelemetry-js
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated circular-json@0.5.9: CircularJSON is in maintenance only, flatted is its successor.

> ref-napi@2.0.3 install /app/node_modules/ref-napi
> node-gyp-build


> ffi-napi@3.0.1 install /app/node_modules/ffi-napi
> node-gyp-build

make: Entering directory '/app/node_modules/ffi-napi/build'
  CC(target) Release/obj.target/nothing/../node-addon-api/src/nothing.o
  AR(target) Release/obj.target/../node-addon-api/src/nothing.a
  COPY Release/nothing.a
  CC(target) Release/obj.target/ffi/deps/libffi/src/prep_cif.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/types.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/raw_api.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/java_raw_api.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/closures.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/ffi.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/ffi64.o
../deps/libffi/src/x86/ffi64.c: In function 'classify_argument':
../deps/libffi/src/x86/ffi64.c:181:18: warning: suggest braces around empty body in an 'else' statement [-Wempty-body]
    FFI_ASSERT (0);
                  ^
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/unix64.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/sysv.o
  AR(target) Release/obj.target/deps/libffi/libffi.a
  COPY Release/libffi.a
  CXX(target) Release/obj.target/ffi_bindings/src/ffi.o
../src/ffi.cc: In static member function 'static FFI::InstanceData* FFI::InstanceData::Get(Napi::Env)':
../src/ffi.cc:11:54: error: 'napi_get_instance_data' was not declared in this scope
   napi_status status = napi_get_instance_data(env, &d);
                                                      ^
../src/ffi.cc: In function 'Napi::Object BindingHook(Napi::Env, Napi::Object)':
../src/ffi.cc:350:17: error: 'napi_set_instance_data' was not declared in this scope
       }, nullptr);
                 ^
make: *** [Release/obj.target/ffi_bindings/src/ffi.o] Error 1
ffi_bindings.target.mk:116: recipe for target 'Release/obj.target/ffi_bindings/src/ffi.o' failed
make: Leaving directory '/app/node_modules/ffi-napi/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:191:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 4.15.0-107-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /app/node_modules/ffi-napi
gyp ERR! node -v v10.18.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ffi-napi@3.0.1 install: `node-gyp-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ffi-napi@3.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-07-23T07_44_53_906Z-debug.log
ERROR: Service 'myservice' failed to build: The command '/bin/sh -c npm install' returned a non-zero code: 1
```

**Comment by gaurang171** [comment]
I am having the exact same issue for node 10.21.0. did you find a solution?

**Comment by miguelmartinezinf** [comment]
> I am having the exact same issue for node 10.21.0. did you find a solution?

Mainly two options:
- Try to use latest node 10 version (10.22.0), or even 12.
- Downgrade your ibmmq module to 0.9.0 (released 2 years ago...)

**Comment by ibmmqmet** [comment]
v10.20 is minimum version for Node and the ffi-napi component. Now enforced in the ibmmq package.json
